# Video 4: Normalizing Qubits


In [ ]:
import numpy as np


class Qubit:
  def __init__(self,x,y):
    self.x = x
    self.y = y 

  def normalize(self):
    length = np.sqrt(np.abs(self.x)**2 + np.abs(self.y)**2)  #length = sqrt(x^2 + y^2)
    self.x  = self.x/length #amplitude of 0 state
    self.y = self.y/length #ampltide of 1 state

q1 = Qubit(0.12876,5.128367)
print(q1.x, q1.y)

q1.normalize()
print(q1.x,q1.y)

#x^2  + y^2 = 1

print((q1.x**2) + (q1.y**2))










# Video 5: Representing bit operations with matrices


In [ ]:
import numpy as np

q1 = np.array([1/np.sqrt(3), np.sqrt(2)/np.sqrt(3)])
print(q1)

flip = np.array([[0,1],[1,0]])

q2 = np.matmul(flip,q1) # matmul is matrix multiplication so it takes matrix on the left and multiplies by the matrix on the right --> flip * q1

print(q2)

[0.57735027 0.81649658]
[0.81649658 0.57735027]


# Video 6: Operation Composition and Quantum Algorithms


In [ ]:
import numpy as np
flip = np.array([[0,1],[1,0]])
identity = np.array([[1,0],[0,1]])
flipid = np.kron(flip, identity) #finding the kronecker product of the flip matrix and the identity matrix! 
print(flipid)

[[0 0 1 0]
 [0 0 0 1]
 [1 0 0 0]
 [0 1 0 0]]


In [ ]:
q1= np.array([1,0]) 
q2 = np.array([0,1])
q1q2 = np.kron(q1,q2)
print(q1q2)

[0 1 0 0]


In [ ]:
print(np.matmul(flipid, q1q2)) # this just represents the state |1> tensor |1>
print(np.kron(np.array([0,1]),np.array([0,1])))

[0 0 0 1]
[0 0 0 1]


# Video 7: Operation Composition and Quantum Algorithm's


In [ ]:
import numpy as np 
cnot = np.array([[1,0,0,0], [0, 1, 0,0], [0,0,0,1], [0,0,1,0]])
print(cnot)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 0 1]
 [0 0 1 0]]


In [ ]:
flip = np.array([[0,1],[1,0]])
identity = np.array([[1,0],[0,1]])
flipid = np.kron(flip, identity)

algorithm = np.matmul(cnot,flipid) #matmul is a numpy function which multiplies the first parameter matrix by the second parameter matrix 
print(algorithm)

[[0 0 1 0]
 [0 0 0 1]
 [0 1 0 0]
 [1 0 0 0]]


# Video 9: Deutsch's Algorithm 2: The Solution


In [ ]:
import numpy as np

hadamard = 1/np.sqrt(2)*np.array([[1,1],[1,-1]])
print(hadamard)

[[ 0.70710678  0.70710678]
 [ 0.70710678 -0.70710678]]


In [ ]:
import numpy as np

identity = np.array([[1,0],[0,1]])
flip = np.array([[0,1],[1,0]]) 

randnum = np.random.randint(0,2) 

f_balanced = randnum * identity + (1-randnum) * flip 
print('f_balanced:\n', f_balanced)
print()

f_constant = randnum*np.array([[1,1],[0,0]])  + (1 - randnum)*np.array([[0,0],[-1, -1]])
print('f_constant:\n', f_constant)


f_balanced:
 [[0 1]
 [1 0]]

f_constant:
 [[ 0  0]
 [-1 -1]]


In [ ]:
f_total = np.kron(identity, f_balanced)
print(f_total)

[[0 1 0 0]
 [1 0 0 0]
 [0 0 0 1]
 [0 0 1 0]]


In [ ]:
# f_total = np.kron(identity, f_constant) 
# print(f_total)

[[ 0  0  0  0]
 [-1 -1  0  0]
 [ 0  0  0  0]
 [ 0  0 -1 -1]]


In [ ]:
hadamard = 1/np.sqrt(2)*np.array([[1,1],[1,-1]])

algorithm = np.kron(hadamard,hadamard) # start by applying the Hadamard operator to both qubits
algorithm = np.matmul(f_total,algorithm) # apply f(x) next
algorithm = np.matmul(np.kron(hadamard,identity),algorithm) # finally, apply the hadamard operator to the first qubit only
print(algorithm)

[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-1.41421356e+00  0.00000000e+00 -4.59869434e-17  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-4.59869434e-17  0.00000000e+00 -1.41421356e+00  0.00000000e+00]]


In [ ]:
input_state = np.kron(np.array([1,0]),np.array([0,1]))
output_state = np.matmul(algorithm,input_state)
print(input_state)
print(output_state)

[0 1 0 0]
[0. 0. 0. 0.]
